set(KOKKOS_OPTIONS "-DCMAKE_CXX_FLAGS='-std=c++14 -gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++'")
string(APPEND FFLAGS "  -qopt-report -xCORE_AVX2 -no-fma")
string(APPEND CFLAGS "  -qopt-report -xCORE_AVX2 -no-fma")
string(APPEND CXXFLAGS " -gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ ")
set(NETCDF_PATH "$ENV{NETCDF}")
set(PNETCDF_PATH "$ENV{PNETCDF_PATH}")
if (DEBUG)
  string(APPEND CPPDEFS " -DPIO_ENABLE_LOGGING=ON ")
endif()
set(PIO_FILESYSTEM_HINTS "gpfs")
if (MPILIB STREQUAL mpt)
  string(APPEND SLIBS " -mkl=cluster")
endif()
if (MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -mkl")
endif()
